### ISSUE TITLE
I really didn't find maddpg in rllib, and I wonder how I can make it work?

### ISSUE THREAD

**Issue by SunLightFor6** [wsjeon/maddpg-rllib#1]
Thanks.

I installed rllib directly by ```pip install ray[rllib]```, and that happeded.
```
Traceback (most recent call last):
  File "run_maddpg.py", line 5, in <module>
    import ray.rllib.agents.maddpg.maddpg as maddpg
ModuleNotFoundError: No module named 'ray.rllib.agents.maddpg'
```

I wonder why and how.

Thanks a lot :D  

💯  from sincerely a beginner for MARL.

**Comment by wsjeon** [comment]
Hi, thank you for your interest. This work is still in progress to be added to RLlib. You can probably use it soon. I'll inform you when it is available.
