### ISSUE TITLE
Can PPO in RLLib run in conjection with environments from the Multi-Agent Particle Environments (MPE)?

### ISSUE THREAD

**Issue by bmpcc6k** [wsjeon/maddpg-rllib#2]
As we can see, MADDPG can work well in conjection with MPE.
So, I wonder if there is possible that PPO can also work well with MPE?
Thanks a lot :D.

**Comment by wsjeon** [comment]
I haven't tried it with PPO, but I guess it'll work if you use a centralized critic, e.g., when each agent's critic takes all of the agents' observations as their inputs. If you don't use a centralized critic and using PPO independently, that may not work.
