### ISSUE TITLE
My particle world env won't return done=True at all

### ISSUE THREAD

**Issue by gohsyi** [wsjeon/maddpg-rllib#5]
Hi, I ran into a problem that the particle world  environment always returns done=False, which leads to the rollout collecting working all the time but the model never learns. I have fixed this by making some changes in `multiagent_particle_world_env.py`.

However, I don't know how many steps are there in one episode in your setting. I wonder this because different steps leads to different episode rewards.

**Comment by wsjeon** [comment]
Hi. I did my experiments with episode length as 25, which is consistent with [OpenAI MADDPG](https://github.com/openai/maddpg). Also, speaking of termination flags, MPE always returns `done=False` unless you specify it. However, I empirically checked that MADDPG works well for `done=False`

**Comment by gohsyi** [comment]
> Hi. I did my experiments with episode length as 25, which is consistent with [OpenAI MADDPG](https://github.com/openai/maddpg). Also, speaking of termination flags, MPE always returns `done=False` unless you specify it. However, I empirically checked that MADDPG works well for `done=False`

I checked my codes and found it turned out I forgot to set the "horizon" parameter which controls the max steps in one episode. Now it works well. Thank you so much for your timely reply!
